apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      # following is just a arbitrary kv pair
      component: server
  template:
    metadata:
      labels:
        # following is just a arbitrary kv pair
        component: server
    spec:
      containers:
      - name: server
        image: mgmchan1216/multi-server
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: '6379'
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: postgres
          # note following name we use PGPASSWORD because in 
          # key.js of server, it calls for an environment
          # variable called PGPASSWORD instead of POSTGRES_PASSWORD
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: MYPASSWORD
